# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseAssignment' do
 
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  # Pods for FirebaseAssignment

end
