# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GainnTrainn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'JTCalendar', '~> 2.0'
end

target 'GainnTrainnWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GainnTrainnWatch

end

target 'GainnTrainnWatch Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GainnTrainnWatch Extension

end
